name: Send a reminder to watch out for scams
on:
  schedule:
    - cron: '0 */15 * * *'
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "<strong>Keep an eye out for scams:</strong> employees and representatives of Parity and Web3 Foundation will never DM you first, and will never ask you for your mnemonic/seed phrase. Never share your mnemonic/seed phrase or password with anyone, and only enter your mnemonic/seed phrases into trusted websites. Be aware that scammers will often impersonate employees and/or replicate trusted websites. Learn more about how to protect yourself from scams at https://wiki.polkadot.network/docs/en/learn-scams"
         server: "matrix.parity.io"
