name: Send a reminder to the office to open the windows
on:
  schedule:
    - cron: '00,45 08-15/3 * * 1-5'
    - cron: '30 09-16/3 * * 1-5'
    - cron: '15 10-17/3 * * 1-5'
jobs:
  ping_matrix:
   runs-on: ubuntu-latest
   steps:
     - name: send message
       uses: s3krit/matrix-message-action@v0.0.3
       with:
         room_id: ${{ secrets.MATRIX_ROOM_ID }}
         access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
         message: "Please open the windows, it's been 45 minutes."
         formatted_message: "<strong>Please open the windows, it's been 45 minutes.</strong>"
         server: "matrix.parity.io"
